// <auto-generated />
using System;
using Gymopedia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gymopedia.Data.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20220917173601_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gymopedia.Domain.Models.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OwnerCoachId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Calendar");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoachId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.ClientIdsList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientOfThisCoachId")
                        .HasColumnType("integer");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ClientIdsList");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalendarId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.CoachIdsList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int>("ThisCoachId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("CoachIdsList");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.CoachWorkDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalendarId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.ToTable("CoachWorkDays");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int?>("CoachWorkDayId")
                        .HasColumnType("integer");

                    b.Property<int>("CoachWorkDayIdOwner")
                        .HasColumnType("integer");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Until")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CoachWorkDayId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.Client", b =>
                {
                    b.HasOne("Gymopedia.Domain.Models.Coach", null)
                        .WithMany("Clients")
                        .HasForeignKey("CoachId");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.ClientIdsList", b =>
                {
                    b.HasOne("Gymopedia.Domain.Models.Session", null)
                        .WithMany("ClientIds")
                        .HasForeignKey("SessionId");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.Coach", b =>
                {
                    b.HasOne("Gymopedia.Domain.Models.Calendar", "Calendar")
                        .WithMany()
                        .HasForeignKey("CalendarId");

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.CoachIdsList", b =>
                {
                    b.HasOne("Gymopedia.Domain.Models.Client", null)
                        .WithMany("CoachIds")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.CoachWorkDay", b =>
                {
                    b.HasOne("Gymopedia.Domain.Models.Calendar", null)
                        .WithMany("CoachWorkDays")
                        .HasForeignKey("CalendarId");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.Session", b =>
                {
                    b.HasOne("Gymopedia.Domain.Models.Client", null)
                        .WithMany("TrainingSessions")
                        .HasForeignKey("ClientId");

                    b.HasOne("Gymopedia.Domain.Models.CoachWorkDay", null)
                        .WithMany("Sessions")
                        .HasForeignKey("CoachWorkDayId");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.Calendar", b =>
                {
                    b.Navigation("CoachWorkDays");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.Client", b =>
                {
                    b.Navigation("CoachIds");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.Coach", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.CoachWorkDay", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Gymopedia.Domain.Models.Session", b =>
                {
                    b.Navigation("ClientIds");
                });
#pragma warning restore 612, 618
        }
    }
}
